server:
  port: 6068
spring:
  application:
    name: ems-statistic-service
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.150:8848
    sentinel:
      transport:
        dashboard: 192.168.136.150:8858 #centinel控制台地址
      web-context-unify: false #关闭context整合

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/ems?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ems.api.domain.po

#nacos:
#  config:
#    server-addr: 192.168.136.150:8848
#    namespace: 7581545a-b1f1-4b00-9f92-58b64c0bd13d #创建的dev命名空间
#    data-id: system-srevice.yml #指定data-id，文件名随便定义
#    auto-refresh: true #必须设置启动自动刷新，才可实现动态刷新
#    bootstrap:
#      enable: true #必须启动bootstrap的支持
#      log-enable: true
#    type: yaml #必须设置文件类型，默认properties属性文件